### ISSUE TITLE
Failed to build on Ubuntu 14.04

### ISSUE THREAD

**Issue by Saentist** [Barracuda09/SATPI#196]
```make
make
g++ -c  -I src -std=c++17 -Werror=vla -Wall -Wextra -Winit-self -Wshadow -pthread  -O2 -s -DNDEBUG -DHAS_NP_FUNCTIONS src/Version.cpp -o obj/Version.o
g++: error: unrecognized command line option ‘-std=c++17’
make: *** [obj/Version.o] Error 1

```

I removed `-std=c++17` but new problem come
```make
make
g++ -c  -I src -Werror=vla -Wall -Wextra -Winit-self -Wshadow -pthread  -O2 -s -DNDEBUG -DHAS_NP_FUNCTIONS src/Version.cpp -o obj/Version.o
g++ -c  -I src -Werror=vla -Wall -Wextra -Winit-self -Wshadow -pthread  -O2 -s -DNDEBUG -DHAS_NP_FUNCTIONS src/InterfaceAttr.cpp -o obj/InterfaceAttr.o
In file included from src/Log.h:23:0,
                 from src/InterfaceAttr.cpp:22:
src/StringConverter.h:27:23: fatal error: string_view: No such file or directory
 #include <string_view>
                       ^
compilation terminated.
make: *** [obj/InterfaceAttr.o] Error 1
```

Any suggestions?

**Comment by Barracuda09** [comment]
Hi @Saentist 

Yes to compile SatPI you need to have at least GCC version 8.3.

the Backport is probably not up to date and can not be patched against the current code
